# Install mongodb 
---
- name: Add mongo ppa key
  become: true
  apt_key: >
    keyserver=hkp://keyserver.ubuntu.com:80
    id=68818C72E52529D4
    state=present
- name: Add mongo sources list
  become: true
  lineinfile: >
    line="deb http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse"
    dest=/etc/apt/sources.list.d/mongodb-org-4.0.list
    state=present
    create=yes
- name: Install mongo
  become: true
  apt: name=mongodb-org state=latest update_cache=yes