# Install apache2
- name: install nodejs
  become: true
  apt:
     name: nodejs
     update_cache: yes
     state: latest
- name: install npm
  become: true
  apt: 
    name: npm
- name: install build-essential
  become: true
  apt: 
    name: build-essential
